import { ApiProperty } from '@nestjs/swagger';
import {
  IsEnum,
  IsEmail,
  IsString,
  IsNotEmpty,
  IsObject,
  ValidateNested,
  IsNumberString,
  IsOptional,
} from 'class-validator';
import { Type } from 'class-transformer';

import { UserRoles } from '../schemas/user.schema';
import { Address } from '../schemas/user.schema';

class AddressDto {
  @IsString()
  @IsOptional()
  @ApiProperty()
  addressLine1: string;

  @IsString()
  @IsOptional()
  @ApiProperty()
  addressLine2: string;

  @IsString()
  @IsOptional()
  @ApiProperty()
  city: string;

  @IsString()
  @IsOptional()
  @ApiProperty()
  state: string;

  @IsString()
  @IsOptional()
  @ApiProperty()
  country: string;
}

export class CreateUserDto {
  @IsString()
  @ApiProperty({ description: 'id of 12 characters generated by cuid / @paralleldrive/cuid2', example: 'sulvi4d384av' })
  @IsNotEmpty()
  _id: string;

  @IsString()
  @ApiProperty({ example: 'Hassan Naveed' })
  @IsNotEmpty()
  name: string;

  @IsString()
  @IsEmail()
  @IsNotEmpty()
  @ApiProperty({ example: 'hassannaveed24@gmail.com' })
  email: string;

  @IsObject()
  @ValidateNested()
  @IsOptional()
  @ApiProperty({ type: AddressDto })
  @Type(() => AddressDto)
  address?: Address;

  @ApiProperty({
    enum: UserRoles,
    example: UserRoles.MEMBER,
  })
  @IsNotEmpty()
  @IsEnum(UserRoles)
  role: UserRoles;

  @ApiProperty({ example: '+923415615279' })
  @IsString()
  @IsOptional()
  phoneNo?: string;
}

export class FindAllQueryDto {
  @IsNumberString()
  @ApiProperty({ example: 50 })
  skip: number;

  @IsNumberString()
  @ApiProperty({ example: 10 })
  take: number;
}
